[Fix✏️]폴더별 요약 칸 조정
Pororii/PoSSG pull request #32
Opened 2024-08-14 07:37 UTC by katekim512

## #️⃣연관된 이슈

#16 

## 💡 핵심적으로 구현된 사항
<img width="1698" alt="image" src="https://github.com/user-attachments/assets/e4db655f-5995-40f3-b7b3-a3c89e8ce31e">

- 폴더별 요약 칸 조정

### 세부 사항
- 사용시 적절한 멘트와 함수 전달해주면 사용 가능

## 🚀 로직 설명 및 코드 설명
 ```
{showDetails && (
                      <div className='pl-10 pr-10 pt-3 pb-3 bg-gray-100 rounded-xl shadow mb-4'>
                        {/* <div className='mt-3' style={{ width: containerWidth }}> */}
                        <span
                          className='block text-sm'
                          style={{ width: '100%' }}
                        >
                          {folderPortfolio}
                        </span>
                      </div>
                      // </div>
                    )}
```
-> 고친 부분 이 부분입니다!

## ➕ 그 외에 추가적으로 구현된 사항

## 🤔 테스트,검증 && 고민 사항
- 오른쪽에 각 단어의 길이가 달라서 끝나는 지점이 다 다른 것으로 보이는데 이 부분 괜찮은지

### 📌 PR Comment 작성 시 Prefix for Reviewers

2024-08-14 12:58 UTC, jiheunkim requested changes

2024-08-14 12:58 UTC, jiheunkim commented on frontend/src/pages/ProjectDetailPage/ProjectDetail.tsx
이거 양쪽 정렬로 해줄 수 있나용? @katekim512

2024-08-16 04:21 UTC, katekim512 commented on frontend/src/pages/ProjectDetailPage/ProjectDetail.tsx
✨넵 했습니당~!

2024-08-16 04:51 UTC, jiheunkim approved these changes
확인완료!

2024-08-16 04:51 UTC, merged